olmeiro/appKreemo

app/Http/Controllers/EncuestaController.php
resources/views/Encuesta/index.blade.php
resources/views/layouts/app.blade.php
routes/web.php

Olme hice la plantilla de encuesta

Se hace plantilla encuesta

---

app/Http/Controllers/VisitaController.php
resources/views/Visita/index.blade.php
resources/views/layouts/app.blade.php
routes/web.php

Se creó controlador, vista y se conectó vista a plantilla.

Se crea vista visitas

---

resources/views/Encuesta/index.blade.php

Olme agregue la vista que hice con diego, esta no es la definitiva, solo estoy ensañando

Se organiza la vista encuesta

---

resources/views/auth/login.blade.php
resources/views/layouts/app.blade.php

cambio pipe

---

app/Http/Controllers/MaquinariaController.php
composer.lock
resources/views/Maquinaria/index.blade.php
resources/views/layouts/app.blade.php
routes/web.php

Maquinaria

---

app/Http/Controllers/ClientesController.php
resources/views/Cliente/contacto.blade.php
resources/views/Cliente/index.blade.php
routes/web.php

Intento de Tabla y conexion vista crear

Se modifica vista Clientes

---

app/Http/Controllers/EncuestaController.php
resources/views/Encuesta/create.blade.php
resources/views/Encuesta/index.blade.php
resources/views/layouts/app.blade.php
routes/web.php

Olme en el subheader estaba en blanco y creería yo que estaba estorbando, de todas formas esta comentado 
Ruta: resources>view>layouts>app.blade.php 
Linea 144 a la 152

Quite el subheader

---

app/Http/Controllers/EncuestaController.php
app/Http/Controllers/ServicioController.php
app/Models/Encuesta.php
app/Models/Servicio.php
resources/views/Cliente/create.blade.php
resources/views/Encuesta/create.blade.php
resources/views/Encuesta/index.blade.php
resources/views/Servicio/index.blade.php
resources/views/layouts/app.blade.php
routes/web.php

Encuesta finalizada - Servicio en proceso

---

app/Http/Controllers/CotizacionController.php
app/Http/Controllers/EstadoCotizacionController.php
app/Http/Controllers/EtapaController.php
app/Http/Controllers/JornadaController.php
app/Http/Controllers/ModalidadController.php
app/Http/Controllers/TipoConcretoController.php
app/Models/EstadoCotizacion.php
app/Models/Etapa.php
app/Models/Jornada.php
app/Models/Modalidad.php
app/Models/TipoConcreto.php
composer.lock
resources/views/Componentes/index.blade.php
resources/views/Cotizacion/create.blade.php
resources/views/Cotizacion/edit.blade.php
resources/views/Cotizacion/editEstado.blade.php
resources/views/Cotizacion/index.blade.php
resources/views/EstadoCotizacion/create.blade.php
resources/views/EstadoCotizacion/edit.blade.php
resources/views/EstadoCotizacion/index.blade.php
resources/views/Maquinaria/index.blade.php
resources/views/layouts/app.blade.php
routes/web.php

se crean  modelos y controladores para  las tablas Estado de la  cotizacion, Etapa, Modalidad, Tipo concreto, Jornada.  asi mismo se desde la  cotizacion se  estan llamando los modelos  necesarios para  el  funcionamiento:
Empresa.
Obra.
Jornada.
Etapa.
Modalidad.
Tipo Concreto.
Estado Cotizacion.
Maquinaria.
Operario.

se crean las vistas de las tablas relacianadas con la cotizacion

---

app/Http/Controllers/ClientesController.php
app/Http/Controllers/CotizacionController.php
app/Http/Middleware/RedirectIfAuthenticated.php
resources/views/Cliente/index.blade.php
resources/views/Cotizacion/index.blade.php
routes/web.php

Agregue modal para crear contactos y tipo de contacto

Modal Contactos

---

app/Http/Controllers/ClientesController.php
public/js/tipoContactoVal.js
resources/views/Cliente/index.blade.php

Primer adelanto en clientes con Ajax

Validaciones

---

resources/views/layouts/app.blade.php

ruta usuarioooo

---

app/Http/Controllers/ClientesController.php
app/Http/Controllers/EmpresaController.php
resources/views/empresa/index.blade.php
resources/views/obracontacto/index.blade.php
resources/views/obracontacto/listar.blade.php

cuadre botones

---

app/Http/Controllers/ClientesController.php
app/Http/Controllers/EmpresaController.php
app/Http/Controllers/ObraContactoController.php
public/js/validacionCliente.js
public/js/validacionObraContacto.js
resources/views/Cliente/index.blade.php
resources/views/obracontacto/index.blade.php

Se alistan validaciones para Contactos de obra
se modifican cards

Validacion Contactos de Obra

---

app/Http/Controllers/ClientesController.php
app/Models/Cliente.php
public/js/validacionCliente.js
public/js/validacionEmpresa.js
public/js/validacionObraContacto.js
resources/views/Cliente/index.blade.php
resources/views/empresa/index.blade.php
resources/views/obracontacto/index.blade.php
resources/views/tipocontacto/index.blade.php

Validar si validaciones valida

validacion empresa

---

app/Http/Controllers/VisitaController.php
app/Http/Controllers/VisitaController1.php
app/Models/Visita.php
public/js/validacionVisita.js
public/js/validacionVisita1.js
resources/views/Visita/index.blade.php
routes/web.php

REvisar Editar de full calendar , faltan validaciones y retoques

Editar Full Calendar

---

app/Http/Controllers/ObraContactoController.php
app/Http/Controllers/UserController.php
app/Http/Kernel.php
app/Http/Middleware/ValidarRol.php
app/Models/User.php
public/js/validacionCliente.js
public/js/validacionListaChequeo.js
public/js/validacionVisita1.js
resources/views/Cliente/index.blade.php
resources/views/TipoConcreto/index.blade.php
resources/views/empresa/index.blade.php
resources/views/layouts/app.blade.php
resources/views/listachequeo/create.blade.php
routes/web.php

Se generan roles para los usuarios

Generando Roles

---

app/Http/Controllers/CotizacionController.php
app/Models/User.php
resources/views/Cotizacion/index.blade.php
resources/views/Cotizacion/informe.blade.php

se realizan  cambios, al  buscar el reporte de la  cotización este  llama al Id de la  cotización y al nombre de la obra.

cambios en el reporte

---

app/Http/Controllers/ClientesController.php
app/Http/Controllers/CotizacionController.php
app/Http/Controllers/EmpresaController.php
app/Http/Controllers/ObraContactoController.php
app/Http/Controllers/ObraController.php
app/Models/Cliente.php
app/Models/Empresa.php
app/Models/Obra.php
app/Models/User.php
public/js/validacionCliente.js
public/js/validacionEmpresa.js
public/js/validacionObraContacto.js
resources/views/Cliente/create.blade.php
resources/views/Cliente/edit.blade.php
resources/views/Cliente/index.blade.php
resources/views/empresa/index.blade.php
resources/views/obra/create.blade.php
resources/views/obra/edit.blade.php
resources/views/obra/index.blade.php
resources/views/obracontacto/listar.blade.php
routes/web.php

Intentanto subir nuevos cambios del modulo clientes

Estado empresa

---

app/Http/Controllers/ChartController.php
app/Models/User.php
resources/views/chart/clienteai.blade.php
routes/web.php

Señor Olmeiro, estuve intentando hacer el reporte de su modulo y no me da, aunque creo saber porque puede ser.. voy a hablar con pipe que es el Master para eso, de todas formas lo subo para tenerlo en cuenta ya que hay mucho avance en esa parte :3 👍

Reporte cliente (falta)

---

public/css/home.css
public/css/styleCotizacion.css
resources/views/Cliente/index.blade.php
resources/views/Cotizacion/index.blade.php
resources/views/Cotizacion/informe.blade.php
resources/views/Encuesta/create.blade.php
resources/views/Encuesta/index.blade.php
resources/views/Servicio/edit.blade.php
resources/views/chart/clienteai.blade.php
resources/views/chart/encuesta.blade.php
resources/views/chart/encuesta4.blade.php
resources/views/chart/encuesta5.blade.php
resources/views/chart/estadosCotizacion.blade.php
resources/views/chart/index.blade.php
resources/views/chart/visita.blade.php
resources/views/empresa/index.blade.php
resources/views/home.blade.php
resources/views/listachequeo/create.blade.php
resources/views/listachequeo/edit.blade.php
resources/views/obra/index.blade.php

Se adecua responsive en prueba en cel samsung g5
